### ISSUE TITLE
HOME environment variable might not be available on Windows

### ISSUE THREAD

**Issue by tinhdv** [bellingard/sonar-scanner-npm#12]
I'm integrating Sonar to my nodejs project and when I run gulp to execute sonar, I got following error:

[11:43:47] 'sonar' errored after 61 ms
[11:43:47] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at getSonarQubeScannerExecutable (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\sonarqube-scanner\dist\sonarqub
e-scanner-executable.js:58:30)
    at scan (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\sonarqube-scanner\dist\index.js:21:5)
    at Gulp.<anonymous> (C:\Users\IBM_ADMIN\AR_Projects\ar-api\gulpfile.js:103:3)
    at module.exports (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\orchestrator\index.js:134:8)
    at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20

**Comment by bellingard** [comment]
Which Node version are you using? Are you on a 32bit Windows installation?

Looks like the problem is similar to what is described here: https://stackoverflow.com/questions/9080085/node-js-find-home-directory-in-platform-agnostic-way

To confirm this, can you try the following:

1. Open `C:\Users\IBM_ADMIN\AR_Projects\ar-api\node_modules\sonarqube-scanner\dist\sonarqub
e-scanner-executable.js`
2. At line #58, replace `process.env.HOME` by `require('os').homedir()`
3. Try to execute the analysis and see if it succeeds or not

**Comment by tinhdv** [comment]
I'm using Node V6.9.2 and on 64bit windows. Let me try with your recommendation

**Comment by tinhdv** [comment]
I confirm that your recommendation is working, could you update the code for windows ? so other people will not face same issue.

Thank you so much @bellingard!

**Comment by bellingard** [comment]
Thanks for the confirmation, I will push a fix soon.
And thanks for reporting the bug!

**Comment by bellingard** [comment]
@tinhdv New version is published, enjoy!

**Comment by tinhdv** [comment]
Cool!
