### ISSUE TITLE
Node 8 execution broke

### ISSUE THREAD

**Issue by felipecafu95** [bellingard/sonar-scanner-npm#167]
Hello,
Recently after the latest update of the package, our pipeline for nodejs 8 has broke.

We use `npx sonarqube-scanner` command to execute the scanner of Sonar.

The command stops the pipeline with the message below:
`Console expects a writable stream instance`

Output from our pipeline (Jenkins):
```console
Started by user Felipe Gomes da Silva
Running as Felipe Gomes da Silva
Obtained Jenkinsfile from 780058180ba9807bb55a70f276e2336fae542b97
Resume disabled by user, switching to high-performance, low-durability mode.
[Bitbucket] Notifying commit build result
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Created Pod: infra jenkins-agents/desenvolvimento-vbp-ui-ec-master-18-m92zt-1gd7d-wbmj6
Agent desenvolvimento-vbp-ui-ec-master-18-m92zt-1gd7d-wbmj6 is provisioned from template desenvolvimento_vbp_ui-ec_master_18-m92zt-1gd7d
Running on desenvolvimento-vbp-ui-ec-master-18-m92zt-1gd7d-wbmj6 in /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] sh
+ grep 'sonar.projectKey=' sonar-project.properties
[Pipeline] sh
+ git --no-pager show -s '--format=%ae'
[Pipeline] sh
+ grep 'sonar.projectName=' sonar-project.properties
[Pipeline] sh
+ git config --get remote.origin.url
[Pipeline] sh
+ git --no-pager show -s '--format=%H'
[Pipeline] readJSON
[Pipeline] withEnv
[Pipeline] {
[Pipeline] ansiColor
[Pipeline] {

[Pipeline] stage
[Pipeline] { (Valida configuracoes)
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ grep -rni npmrc .gitignore
30:.npmrc
[Pipeline] echo
==> Informando versao do npm:
[Pipeline] sh
+ npm version
{ 'ui-ec': '1.17.76',
  npm: '6.13.4',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '4',
  nghttp2: '1.39.2',
  node: '8.17.0',
  openssl: '1.0.2s',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.23.2',
  v8: '6.2.414.78',
  zlib: '1.2.11' }
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Instala dependencias)
[Pipeline] script
[Pipeline] {
[Pipeline] withNPM
Using settings config with name npmrc
A workscape local .npmrc already exists and will be overwrriten for the build.
Writing .npmrc file: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/.npmrc
[Pipeline] {
[Pipeline] sh
+ npm ci

> es5-ext@0.10.62 postinstall /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> fsevents@1.2.13 install /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/node_modules/glob-watcher/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported
added 1250 packages in 17.981s
[Pipeline] }
[Pipeline] // withNPM
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Teste Unitario)
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ npm test -- --coverage

> ui-ec@1.17.76 test /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master
> echo "Error: no test specified" && exit 0 "--coverage"

Error: no test specified
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (SonarQube)
[Pipeline] stage
[Pipeline] { (Executando sonarqube scanner)
[Pipeline] script
[Pipeline] {
[Pipeline] withSonarQubeEnv
Injecting SonarQube environment variables using the configuration: sonarqube-prd-lts
[Pipeline] {
[Pipeline] sh
+ npx sonarqube-scanner
npx: installed 86 in 10.408s
Console expects a writable stream instance
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeed?
[Pipeline] { (Teste de Frontend)
Stage "Teste de Frontend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] office365ConnectorSend
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }

[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
Finished: FAILURE
```
We have tested with the release `2.9.0` and all works as expected, different from the latest version (2.9.1).
Using version `2.9.0` solved our problem...

Output using the `2.9.0` version:

```console
Started by user Felipe Gomes da Silva
Running as Felipe Gomes da Silva
Obtained Jenkinsfile from 780058180ba9807bb55a70f276e2336fae542b97
Resume disabled by user, switching to high-performance, low-durability mode.
[Bitbucket] Notifying commit build result
[Pipeline] Start of Pipeline
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Created Pod: infra jenkins-agents/desenvolvimento-vbp-ui-ec-master-19-161c4-2sh3l-4p65h
Running on desenvolvimento-vbp-ui-ec-master-19-161c4-2sh3l-4p65h in /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] container
[Pipeline] {
[Pipeline] sh
+ grep 'sonar.projectKey=' sonar-project.properties
[Pipeline] sh
+ git --no-pager show -s '--format=%ae'
[Pipeline] sh
+ grep 'sonar.projectName=' sonar-project.properties
[Pipeline] sh
+ git config --get remote.origin.url
[Pipeline] sh
+ git --no-pager show -s '--format=%H'
[Pipeline] readJSON
[Pipeline] withEnv
[Pipeline] {
[Pipeline] ansiColor
[Pipeline] {

[Pipeline] stage
[Pipeline] { (Valida configuracoes)
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ grep -rni npmrc .gitignore
30:.npmrc
[Pipeline] echo
==> Informando versao do npm:
[Pipeline] sh
+ npm version
{ 'ui-ec': '1.17.76',
  npm: '6.13.4',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '4',
  nghttp2: '1.39.2',
  node: '8.17.0',
  openssl: '1.0.2s',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.23.2',
  v8: '6.2.414.78',
  zlib: '1.2.11' }
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Instala dependencias)
[Pipeline] script
[Pipeline] {
[Pipeline] withNPM
Using settings config with name npmrc
A workscape local .npmrc already exists and will be overwrriten for the build.
Writing .npmrc file: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/.npmrc
[Pipeline] {
[Pipeline] sh
+ npm ci

> es5-ext@0.10.62 postinstall /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


> fsevents@1.2.13 install /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/node_modules/glob-watcher/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported
added 1250 packages in 23.525s
[Pipeline] }
[Pipeline] // withNPM
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Teste Unitario)
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ npm test -- --coverage

> ui-ec@1.17.76 test /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master
> echo "Error: no test specified" && exit 0 "--coverage"

Error: no test specified
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (SonarQube)
[Pipeline] stage
[Pipeline] { (Executando sonarqube scanner)
[Pipeline] script
[Pipeline] {
[Pipeline] withSonarQubeEnv
Injecting SonarQube environment variables using the configuration: sonarqube-prd-lts
[Pipeline] {
[Pipeline] sh
+ npx sonarqube-scanner@2.9.0
npx: installed 90 in 11.715s
[09:29:54] Starting analysis...
[09:29:54] Checking if executable exists: /home/jenkins/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner
[09:29:54] Platform binaries for SonarScanner found. Using it.
INFO: Scanner configuration file: /home/jenkins/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/sonar-project.properties
INFO: SonarScanner 4.7.0.2747
INFO: Java 11.0.16 Amazon.com Inc. (64-bit)
INFO: Linux 5.4.209-116.363.amzn2.x86_64 amd64
INFO: User cache: /home/jenkins/.sonar/cache
INFO: Scanner configuration file: /home/jenkins/.sonar/native-sonar-scanner/sonar-scanner-4.7.0.2747-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/sonar-project.properties
INFO: Analyzing on SonarQube server 8.9.9
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Load global settings
INFO: Load global settings (done) | time=91ms
INFO: Server id: 68551417-AYN7rC1gN0djS6c82rZp
INFO: User cache: /home/jenkins/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=59ms
INFO: Load/download plugins (done) | time=2069ms
INFO: Process project properties
INFO: Process project properties (done) | time=10ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=2ms
INFO: Project key: ui-ec
INFO: Base dir: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master
INFO: Working dir: /home/jenkins/agent/workspace/desenvolvimento_vbp_ui-ec_master/.scannerwork
INFO: Load project settings for component key: 'ui-ec'
INFO: Load project settings for component key: 'ui-ec' (done) | time=19ms
INFO: Auto-configuring with CI 'Jenkins'
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=54ms
INFO: Auto-configuring with CI 'Jenkins'
INFO: Load active rules
INFO: Load active rules (done) | time=984ms
INFO: Indexing files...
INFO: Project configuration:
INFO:   Excluded sources: js/test/**/*.spec.js, js/test/**/*.spec.jsx, js/test/**/*.test.js, js/test/**/*.test.jsx
INFO:   Included tests: js/test/**/*.spec.js, js/test/**/*.spec.jsx, js/test/**/*.test.js, js/test/**/*.test.jsx
INFO: Load project repositories
INFO: Load project repositories (done) | time=17ms
INFO: 26 files indexed
INFO: 26 files ignored because of inclusion/exclusion patterns
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for js: Sonar way
INFO: ------------- Run sensors on module ui-ec
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=34ms
INFO: Sensor CSS Rules [cssfamily]
INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
INFO: Sensor CSS Rules [cssfamily] (done) | time=1ms
INFO: Sensor C# Project Type Information [csharp]
INFO: Sensor C# Project Type Information [csharp] (done) | time=1ms
INFO: Sensor C# Properties [csharp]
INFO: Sensor C# Properties [csharp] (done) | time=1ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=1ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=4ms
INFO: Sensor VB.NET Project Type Information [vbnet]
INFO: Sensor VB.NET Project Type Information [vbnet] (done) | time=1ms
INFO: Sensor VB.NET Properties [vbnet]
INFO: Sensor VB.NET Properties [vbnet] (done) | time=1ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JavaScript analysis [javascript]

INFO: Analysis total time: 5:06.252 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 5:11.590s
INFO: Final Memory: 18M/226M
INFO: ------------------------------------------------------------------------
[09:35:06] Analysis finished.
[Pipeline] echo
==> Analise do sonar disponivel em: http://sonarqub.cluster.local:9000/dashboard?id=ui-ec
.
[Pipeline] }
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Avaliaçao do Quality Gate)
[Pipeline] script
[Pipeline] {
[Pipeline] withSonarQubeEnv
Injecting SonarQube environment variables using the configuration: sonarqube-prd-lts
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] waitForQualityGate
Checking status of SonarQube task 'AYTxu3n0qXCJTicOnQEf' on server 'sonarqube-prd-lts'
SonarQube task 'AYTxu3n0qXCJTicOnQEf' status is 'SUCCESS'
SonarQube task 'AYTxu3n0qXCJTicOnQEf' completed. Quality gate is 'OK'
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Teste de Frontend)
[Pipeline] script
[Pipeline] {
[Pipeline] build
Scheduling project: Testing Lab » Testes funcionais » frontend-cicd
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] office365ConnectorSend
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }

[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
Finished: SUCCESS
```

Executing with debug mode with `2.9.1` version:

```console
bash-5.0# npx --node-arg=--inspect sonarqube-scanner
npx: installed 86 in 24.488s
Debugger listening on ws://127.0.0.1:9229/33d5b85b-c142-4da8-ab8b-16570f72be51
For help see https://nodejs.org/en/docs/inspector
console.js:35
    throw new TypeError('Console expects a writable stream instance');
    ^

TypeError: Console expects a writable stream instance
    at new Console (console.js:35:11)
    at Object.<anonymous> (/root/.npm/_npx/586/lib/node_modules/sonarqube-scanner/node_modules/fancy-log/index.js:7:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.npm/_npx/586/lib/node_modules/sonarqube-scanner/src/index.js:2:13)
```

Thanks

**Comment by saberduck** [comment]
hello @felipecafu95 , 

sorry for the inconvenience. It looks like the update to `fancy-log` broke backward compatibility and we are no longer able to run on Node 8. I would strongly suggest upgrading to a more recent Node.js version (the current LTS is 18). If that's not possible, you can downgrade to the previous version `2.9.0`.

In the next release, we are going to update Node.js requirement anyway and we will properly bump the major version of the package to follow semantic versioning.

**Comment by felipecafu95** [comment]
great @saberduck, thanks for the explanation.
we are using the previous version `2.9.0` until the dev team upgrade node engine.

thanks again.
