### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by adrianovieira** [bellingard/sonar-scanner-npm#94]
Hi, folks!

Please,
how/where do I update to increase limits for this thing?

```
22:13:33.941 ERROR: ClientError [PayloadTooLargeError]: request entity too large
22:13:33.942 ERROR:     at readStream (/work/.scannerwork/css-bundle/node_modules/raw-body/index.js:155:17)
22:13:33.942 ERROR:     at getRawBody (/work/.scannerwork/css-bundle/node_modules/raw-body/index.js:108:12)
22:13:33.942 ERROR:     at read (/work/.scannerwork/css-bundle/node_modules/body-parser/lib/read.js:77:3)
22:13:33.942 ERROR:     at jsonParser (/work/.scannerwork/css-bundle/node_modules/body-parser/lib/types/json.js:135:5)
22:13:33.942 ERROR:     at Layer.handle [as handle_request] (/work/.scannerwork/css-bundle/node_modules/express/lib/router/layer.js:95:5)
22:13:33.942 ERROR:     at trim_prefix (/work/.scannerwork/css-bundle/node_modules/express/lib/router/index.js:317:13)
22:13:33.942 ERROR:     at /work/.scannerwork/css-bundle/node_modules/express/lib/router/index.js:284:7
22:13:33.942 ERROR:     at Function.process_params (/work/.scannerwork/css-bundle/node_modules/express/lib/router/index.js:335:12)
22:13:33.942 ERROR:     at next (/work/.scannerwork/css-bundle/node_modules/express/lib/router/index.js:275:10)
22:13:33.942 ERROR:     at expressInit (/work/.scannerwork/css-bundle/node_modules/express/lib/middleware/init.js:40:5) {
22:13:33.942 ERROR:   expected: 643473,
22:13:33.942 ERROR:   length: 643473,
22:13:33.942 ERROR:   limit: 102400,
22:13:33.942 ERROR:   type: 'entity.too.large'
22:13:33.942 ERROR: }
```

**Comment by himanshusinghs** [comment]
Facing the same issue, any update here?

**Comment by gabssnake** [comment]
Hey guys, are you still having this issue?

**Comment by gabssnake** [comment]
Closing this as stale. Feel free to reopen in new information comes up.
